name: Deploy Dockerized App to Azure

on:
  push:
    branches:
      - main # Le déploiement se fait sur la branche principale

env:
  # VOS RESSOURCES AZURE
  AZURE_WEBAPP_NAME: Hajar-docker-test        # Le nom de votre App Service
  ACR_LOGIN_SERVER: hajarregistrytest01.azurecr.io # Le nom de votre Container Registry
  IMAGE_NAME: hajar-docker-test               # Nom de l'image (doit correspondre au nom de l'App Service)
  IMAGE_TAG: ${{ github.sha }}                # Utilisation du Hash de commit pour un tag unique

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # 1. Récupère le code de GitHub

      # 2. Connexion à Azure avec le Secret (Service Principal)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Utilise le JSON secret que vous avez stocké

      # 3. Construction de l'Image Docker
      - name: Build Docker Image
        # Construit l'image et lui donne le tag complet pour l'ACR
        run: docker build . --tag ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.IMAGE_TAG }}

      # 4. Connexion et Pousser l'Image vers ACR
      - name: Push Docker Image to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          # Azure s'authentifie automatiquement avec les AZURE_CREDENTIALS
          username: ${{ secrets.AZURE_CLIENT_ID }} 
          password: ${{ secrets.AZURE_CLIENT_SECRET }} 
      - name: Push to Registry
        run: docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.IMAGE_TAG }}
        
      # 5. Déploiement vers Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          # Déploie l'image que nous venons de créer
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.IMAGE_TAG }}